version: '3'

services: 
    scraper-api: 
         build:  
            dockerfile:  Dockerfile
            context: ./scraper
         volumes: 
             -  /app/node_modules
             - ./scraper:/app
         ports: 
            - 5000:5000