version: "3"
services:
  scraper-api:
    environment:
      - DISPLAY=:99
    command: >
      sh -c "Xvfb :99 -screen 0 1024x768x16 &
            yarn run start"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./scraper:/app
    ports:
      - 5000:5000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./persistance/mongo:/data
    ports:
      - 27017:27017
